[project]
name = "enonomics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geojson-pydantic>=2.2.0",
    "networkx>=3.7",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyproj>=3.8.0",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "scipy>=1.18.1",
    "typer>=0.27.2",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.8",
    "scipy-stubs>=1.18.1.1",
    "types-networkx>=3.6.1.20260911",
    "types-pyyaml>=6.0.12.20250809",
]

[tool.ruff]
line-length = 100
